In [289]:
import pandas as pd
print(pd.__version__)

3.0.6

In [290]:
df = pd.read_csv("ECommerce_Orders_.csv")
print(df.to_string())

   Order_ID      Customer       City     Category     Product  Quantity  Unit_Price Payment_Mode  Rating
0    ORD001  Rahul Sharma  Hyderabad  Electronics      Laptop         1       65000          UPI       5
1    ORD002   Priya Reddy  Bangalore     Clothing     T-Shirt         2        1200         Card       4
2    ORD003   Arjun Kumar  Hyderabad  Electronics      Mobile         1       25000          UPI       5
3    ORD004     Sneha Rao    Chennai         Home       Mixer         1        5000         Cash       3
4    ORD005     Kiran Das       Pune  Electronics  Headphones         2        3000         Card       4
5    ORD006  Rahul Sharma  Hyderabad     Clothing       Jeans         1        2200          UPI       5
6    ORD007  Anjali Singh     Mumbai  Electronics     Monitor         1       18000         Card       4
7    ORD008  Vikram Patel  Bangalore         Home       Chair         2        7500          UPI       3
8    ORD009   Priya Reddy  Bangalore     Clothing       Shoes         1        2500         Card       4
9    ORD010   Rohit Verma      Delhi  Electronics    Keyboard         3        1500         Cash       5
10   ORD011   Arjun Kumar  Hyderabad  Electronics      Tablet         1       30000          UPI       5
11   ORD012     Sneha Rao    Chennai     Clothing      Jacket         1        3500         Card       4
12   ORD013     Kiran Das       Pune         Home        Lamp         2        1800         Cash       3
13   ORD014  Anjali Singh     Mumbai  Electronics  Smartwatch         1       12000          UPI       5
14   ORD015  Vikram Patel  Bangalore     Clothing     T-Shirt         2        1200         Card       4

In [291]:
#Task 1 — High-Value Order Investigation


df["Sales"]=df["Quantity"]*df["Unit_Price"]
print(df.to_string())

   Order_ID      Customer       City     Category     Product  Quantity  Unit_Price Payment_Mode  Rating  Sales
0    ORD001  Rahul Sharma  Hyderabad  Electronics      Laptop         1       65000          UPI       5  65000
1    ORD002   Priya Reddy  Bangalore     Clothing     T-Shirt         2        1200         Card       4   2400
2    ORD003   Arjun Kumar  Hyderabad  Electronics      Mobile         1       25000          UPI       5  25000
3    ORD004     Sneha Rao    Chennai         Home       Mixer         1        5000         Cash       3   5000
4    ORD005     Kiran Das       Pune  Electronics  Headphones         2        3000         Card       4   6000
5    ORD006  Rahul Sharma  Hyderabad     Clothing       Jeans         1        2200          UPI       5   2200
6    ORD007  Anjali Singh     Mumbai  Electronics     Monitor         1       18000         Card       4  18000
7    ORD008  Vikram Patel  Bangalore         Home       Chair         2        7500          UPI       3  15000
8    ORD009   Priya Reddy  Bangalore     Clothing       Shoes         1        2500         Card       4   2500
9    ORD010   Rohit Verma      Delhi  Electronics    Keyboard         3        1500         Cash       5   4500
10   ORD011   Arjun Kumar  Hyderabad  Electronics      Tablet         1       30000          UPI       5  30000
11   ORD012     Sneha Rao    Chennai     Clothing      Jacket         1        3500         Card       4   3500
12   ORD013     Kiran Das       Pune         Home        Lamp         2        1800         Cash       3   3600
13   ORD014  Anjali Singh     Mumbai  Electronics  Smartwatch         1       12000          UPI       5  12000
14   ORD015  Vikram Patel  Bangalore     Clothing     T-Shirt         2        1200         Card       4   2400

In [292]:
result=df[
    (df["Category"]=="Electronics")& 
    (df["Sales"]>20000)&
    (df["Rating"]>=4)&
    (df["Payment_Mode"].isin(["UPI","Card"]))]
print(result.to_string())
print("*"*20)
result=result[["Order_ID","Customer","Product","Sales","Rating","Payment_Mode"]]
print(result.to_string())

   Order_ID      Customer       City     Category Product  Quantity  Unit_Price Payment_Mode  Rating  Sales
0    ORD001  Rahul Sharma  Hyderabad  Electronics  Laptop         1       65000          UPI       5  65000
2    ORD003   Arjun Kumar  Hyderabad  Electronics  Mobile         1       25000          UPI       5  25000
10   ORD011   Arjun Kumar  Hyderabad  Electronics  Tablet         1       30000          UPI       5  30000
********************
   Order_ID      Customer Product  Sales  Rating Payment_Mode
0    ORD001  Rahul Sharma  Laptop  65000       5          UPI
2    ORD003   Arjun Kumar  Mobile  25000       5          UPI
10   ORD011   Arjun Kumar  Tablet  30000       5          UPI

In [293]:
#Task 2 — Customer Name Analysis
df["Customer_Upper"]=df["Customer"].str.upper()
print(df.to_string())

   Order_ID      Customer       City     Category     Product  Quantity  Unit_Price Payment_Mode  Rating  Sales Customer_Upper
0    ORD001  Rahul Sharma  Hyderabad  Electronics      Laptop         1       65000          UPI       5  65000   RAHUL SHARMA
1    ORD002   Priya Reddy  Bangalore     Clothing     T-Shirt         2        1200         Card       4   2400    PRIYA REDDY
2    ORD003   Arjun Kumar  Hyderabad  Electronics      Mobile         1       25000          UPI       5  25000    ARJUN KUMAR
3    ORD004     Sneha Rao    Chennai         Home       Mixer         1        5000         Cash       3   5000      SNEHA RAO
4    ORD005     Kiran Das       Pune  Electronics  Headphones         2        3000         Card       4   6000      KIRAN DAS
5    ORD006  Rahul Sharma  Hyderabad     Clothing       Jeans         1        2200          UPI       5   2200   RAHUL SHARMA
6    ORD007  Anjali Singh     Mumbai  Electronics     Monitor         1       18000         Card       4  18000   ANJALI SINGH
7    ORD008  Vikram Patel  Bangalore         Home       Chair         2        7500          UPI       3  15000   VIKRAM PATEL
8    ORD009   Priya Reddy  Bangalore     Clothing       Shoes         1        2500         Card       4   2500    PRIYA REDDY
9    ORD010   Rohit Verma      Delhi  Electronics    Keyboard         3        1500         Cash       5   4500    ROHIT VERMA
10   ORD011   Arjun Kumar  Hyderabad  Electronics      Tablet         1       30000          UPI       5  30000    ARJUN KUMAR
11   ORD012     Sneha Rao    Chennai     Clothing      Jacket         1        3500         Card       4   3500      SNEHA RAO
12   ORD013     Kiran Das       Pune         Home        Lamp         2        1800         Cash       3   3600      KIRAN DAS
13   ORD014  Anjali Singh     Mumbai  Electronics  Smartwatch         1       12000          UPI       5  12000   ANJALI SINGH
14   ORD015  Vikram Patel  Bangalore     Clothing     T-Shirt         2        1200         Card       4   2400   VIKRAM PATEL

In [294]:
df["First_name"]=df["Customer"].str.split().str[0]
print(df.to_string())

   Order_ID      Customer       City     Category     Product  Quantity  Unit_Price Payment_Mode  Rating  Sales Customer_Upper First_name
0    ORD001  Rahul Sharma  Hyderabad  Electronics      Laptop         1       65000          UPI       5  65000   RAHUL SHARMA      Rahul
1    ORD002   Priya Reddy  Bangalore     Clothing     T-Shirt         2        1200         Card       4   2400    PRIYA REDDY      Priya
2    ORD003   Arjun Kumar  Hyderabad  Electronics      Mobile         1       25000          UPI       5  25000    ARJUN KUMAR      Arjun
3    ORD004     Sneha Rao    Chennai         Home       Mixer         1        5000         Cash       3   5000      SNEHA RAO      Sneha
4    ORD005     Kiran Das       Pune  Electronics  Headphones         2        3000         Card       4   6000      KIRAN DAS      Kiran
5    ORD006  Rahul Sharma  Hyderabad     Clothing       Jeans         1        2200          UPI       5   2200   RAHUL SHARMA      Rahul
6    ORD007  Anjali Singh     Mumbai  Electronics     Monitor         1       18000         Card       4  18000   ANJALI SINGH     Anjali
7    ORD008  Vikram Patel  Bangalore         Home       Chair         2        7500          UPI       3  15000   VIKRAM PATEL     Vikram
8    ORD009   Priya Reddy  Bangalore     Clothing       Shoes         1        2500         Card       4   2500    PRIYA REDDY      Priya
9    ORD010   Rohit Verma      Delhi  Electronics    Keyboard         3        1500         Cash       5   4500    ROHIT VERMA      Rohit
10   ORD011   Arjun Kumar  Hyderabad  Electronics      Tablet         1       30000          UPI       5  30000    ARJUN KUMAR      Arjun
11   ORD012     Sneha Rao    Chennai     Clothing      Jacket         1        3500         Card       4   3500      SNEHA RAO      Sneha
12   ORD013     Kiran Das       Pune         Home        Lamp         2        1800         Cash       3   3600      KIRAN DAS      Kiran
13   ORD014  Anjali Singh     Mumbai  Electronics  Smartwatch         1       12000          UPI       5  12000   ANJALI SINGH     Anjali
14   ORD015  Vikram Patel  Bangalore     Clothing     T-Shirt         2        1200         Card       4   2400   VIKRAM PATEL     Vikram

In [295]:
startAR=df[df["First_name"].str.startswith(("A","R"))]
print(startAR[["Customer","First_name"]])

        Customer First_name
0   Rahul Sharma      Rahul
2    Arjun Kumar      Arjun
5   Rahul Sharma      Rahul
6   Anjali Singh     Anjali
9    Rohit Verma      Rohit
10   Arjun Kumar      Arjun
13  Anjali Singh     Anjali

In [296]:
contain_ra =df[df["First_name"].str.contains("ra",case=False)]
print(contain_ra["First_name"])

0      Rahul
4      Kiran
5      Rahul
7     Vikram
12     Kiran
14    Vikram
Name: First_name, dtype: object

In [297]:
df["Name_lenth"]=df["Customer"].str.len()
print(df[["Customer","Name_lenth"]])

        Customer  Name_lenth
0   Rahul Sharma          12
1    Priya Reddy          11
2    Arjun Kumar          11
3      Sneha Rao           9
4      Kiran Das           9
5   Rahul Sharma          12
6   Anjali Singh          12
7   Vikram Patel          12
8    Priya Reddy          11
9    Rohit Verma          11
10   Arjun Kumar          11
11     Sneha Rao           9
12     Kiran Das           9
13  Anjali Singh          12
14  Vikram Patel          12

In [298]:
#Task 3 — Dynamic Sales Classification
import numpy as np
conditions= [df["Sales"]<5000,
             (df["Sales"]>=5000)&(df["Sales"]<=20000),
             (df["Sales"]>20000)&(df["Sales"]<=50000),
             (df["Sales"]>50000)
             ]
choice=["low","Medium","High","Very High"]
df["Sales_Level"]=np.select(conditions,choice,default="unknown")
print(df.to_string())

   Order_ID      Customer       City     Category     Product  Quantity  Unit_Price Payment_Mode  Rating  Sales Customer_Upper First_name  Name_lenth Sales_Level
0    ORD001  Rahul Sharma  Hyderabad  Electronics      Laptop         1       65000          UPI       5  65000   RAHUL SHARMA      Rahul          12   Very High
1    ORD002   Priya Reddy  Bangalore     Clothing     T-Shirt         2        1200         Card       4   2400    PRIYA REDDY      Priya          11         low
2    ORD003   Arjun Kumar  Hyderabad  Electronics      Mobile         1       25000          UPI       5  25000    ARJUN KUMAR      Arjun          11        High
3    ORD004     Sneha Rao    Chennai         Home       Mixer         1        5000         Cash       3   5000      SNEHA RAO      Sneha           9      Medium
4    ORD005     Kiran Das       Pune  Electronics  Headphones         2        3000         Card       4   6000      KIRAN DAS      Kiran           9      Medium
5    ORD006  Rahul Sharma  Hyderabad     Clothing       Jeans         1        2200          UPI       5   2200   RAHUL SHARMA      Rahul          12         low
6    ORD007  Anjali Singh     Mumbai  Electronics     Monitor         1       18000         Card       4  18000   ANJALI SINGH     Anjali          12      Medium
7    ORD008  Vikram Patel  Bangalore         Home       Chair         2        7500          UPI       3  15000   VIKRAM PATEL     Vikram          12      Medium
8    ORD009   Priya Reddy  Bangalore     Clothing       Shoes         1        2500         Card       4   2500    PRIYA REDDY      Priya          11         low
9    ORD010   Rohit Verma      Delhi  Electronics    Keyboard         3        1500         Cash       5   4500    ROHIT VERMA      Rohit          11         low
10   ORD011   Arjun Kumar  Hyderabad  Electronics      Tablet         1       30000          UPI       5  30000    ARJUN KUMAR      Arjun          11        High
11   ORD012     Sneha Rao    Chennai     Clothing      Jacket         1        3500         Card       4   3500      SNEHA RAO      Sneha           9         low
12   ORD013     Kiran Das       Pune         Home        Lamp         2        1800         Cash       3   3600      KIRAN DAS      Kiran           9         low
13   ORD014  Anjali Singh     Mumbai  Electronics  Smartwatch         1       12000          UPI       5  12000   ANJALI SINGH     Anjali          12      Medium
14   ORD015  Vikram Patel  Bangalore     Clothing     T-Shirt         2        1200         Card       4   2400   VIKRAM PATEL     Vikram          12         low

In [299]:

df["Customer_Type"] = np.where(df["Rating"]>= 4,"Satisfied","Needs Attention"
)
print(df[["Order_ID","Sales","Rating","Sales_Level","Customer_Type"]])

   Order_ID  Sales  Rating Sales_Level    Customer_Type
0    ORD001  65000       5   Very High        Satisfied
1    ORD002   2400       4         low        Satisfied
2    ORD003  25000       5        High        Satisfied
3    ORD004   5000       3      Medium  Needs Attention
4    ORD005   6000       4      Medium        Satisfied
5    ORD006   2200       5         low        Satisfied
6    ORD007  18000       4      Medium        Satisfied
7    ORD008  15000       3      Medium  Needs Attention
8    ORD009   2500       4         low        Satisfied
9    ORD010   4500       5         low        Satisfied
10   ORD011  30000       5        High        Satisfied
11   ORD012   3500       4         low        Satisfied
12   ORD013   3600       3         low  Needs Attention
13   ORD014  12000       5      Medium        Satisfied
14   ORD015   2400       4         low        Satisfied

In [300]:
#Task 4 — Product Search System
df["Contain_phone"] = df["Product"].str.contains("phone",case=False)
print(df[df["Contain_phone"]].to_string())

  Order_ID   Customer  City     Category     Product  Quantity  Unit_Price Payment_Mode  Rating  Sales Customer_Upper First_name  Name_lenth Sales_Level Customer_Type  Contain_phone
4   ORD005  Kiran Das  Pune  Electronics  Headphones         2        3000         Card       4   6000      KIRAN DAS      Kiran           9      Medium     Satisfied           True

In [301]:
df["Contain_phone"] = df["Product"].str.contains("lap|tab", case=False, na=False)
print(df[df["Contain_phone"]].to_string())

   Order_ID      Customer       City     Category Product  Quantity  Unit_Price Payment_Mode  Rating  Sales Customer_Upper First_name  Name_lenth Sales_Level Customer_Type  Contain_phone
0    ORD001  Rahul Sharma  Hyderabad  Electronics  Laptop         1       65000          UPI       5  65000   RAHUL SHARMA      Rahul          12   Very High     Satisfied           True
10   ORD011   Arjun Kumar  Hyderabad  Electronics  Tablet         1       30000          UPI       5  30000    ARJUN KUMAR      Arjun          11        High     Satisfied           True

In [302]:
df["Contain_phone"] = df["Product"].str.len()>6
print(df[df["Contain_phone"]].to_string())

   Order_ID      Customer       City     Category     Product  Quantity  Unit_Price Payment_Mode  Rating  Sales Customer_Upper First_name  Name_lenth Sales_Level Customer_Type  Contain_phone
1    ORD002   Priya Reddy  Bangalore     Clothing     T-Shirt         2        1200         Card       4   2400    PRIYA REDDY      Priya          11         low     Satisfied           True
4    ORD005     Kiran Das       Pune  Electronics  Headphones         2        3000         Card       4   6000      KIRAN DAS      Kiran           9      Medium     Satisfied           True
6    ORD007  Anjali Singh     Mumbai  Electronics     Monitor         1       18000         Card       4  18000   ANJALI SINGH     Anjali          12      Medium     Satisfied           True
9    ORD010   Rohit Verma      Delhi  Electronics    Keyboard         3        1500         Cash       5   4500    ROHIT VERMA      Rohit          11         low     Satisfied           True
13   ORD014  Anjali Singh     Mumbai  Electronics  Smartwatch         1       12000          UPI       5  12000   ANJALI SINGH     Anjali          12      Medium     Satisfied           True
14   ORD015  Vikram Patel  Bangalore     Clothing     T-Shirt         2        1200         Card       4   2400   VIKRAM PATEL     Vikram          12         low     Satisfied           True

In [303]:
result = df["Category"]!=("Clothing")
print(df[result].to_string())

   Order_ID      Customer       City     Category     Product  Quantity  Unit_Price Payment_Mode  Rating  Sales Customer_Upper First_name  Name_lenth Sales_Level    Customer_Type  Contain_phone
0    ORD001  Rahul Sharma  Hyderabad  Electronics      Laptop         1       65000          UPI       5  65000   RAHUL SHARMA      Rahul          12   Very High        Satisfied          False
2    ORD003   Arjun Kumar  Hyderabad  Electronics      Mobile         1       25000          UPI       5  25000    ARJUN KUMAR      Arjun          11        High        Satisfied          False
3    ORD004     Sneha Rao    Chennai         Home       Mixer         1        5000         Cash       3   5000      SNEHA RAO      Sneha           9      Medium  Needs Attention          False
4    ORD005     Kiran Das       Pune  Electronics  Headphones         2        3000         Card       4   6000      KIRAN DAS      Kiran           9      Medium        Satisfied           True
6    ORD007  Anjali Singh     Mumbai  Electronics     Monitor         1       18000         Card       4  18000   ANJALI SINGH     Anjali          12      Medium        Satisfied           True
7    ORD008  Vikram Patel  Bangalore         Home       Chair         2        7500          UPI       3  15000   VIKRAM PATEL     Vikram          12      Medium  Needs Attention          False
9    ORD010   Rohit Verma      Delhi  Electronics    Keyboard         3        1500         Cash       5   4500    ROHIT VERMA      Rohit          11         low        Satisfied           True
10   ORD011   Arjun Kumar  Hyderabad  Electronics      Tablet         1       30000          UPI       5  30000    ARJUN KUMAR      Arjun          11        High        Satisfied          False
12   ORD013     Kiran Das       Pune         Home        Lamp         2        1800         Cash       3   3600      KIRAN DAS      Kiran           9         low  Needs Attention          False
13   ORD014  Anjali Singh     Mumbai  Electronics  Smartwatch         1       12000          UPI       5  12000   ANJALI SINGH     Anjali          12      Medium        Satisfied           True

In [304]:
result1 = df[(df["Product"].str.contains("lap|tab", case=False, na=False))
    &(df["Product"].str.len() > 6)&(df["Category"] != "Clothing")]
print(result1[["Product","Category"]])

Empty DataFrame
Columns: [Product, Category]
Index: []

In [ ]:
# 1. Products containing 'phone'
phone_products = df[
    df["Product"].str.contains("phone", case=False, na=False)
]

print("Products containing 'phone':")
print(phone_products[["Product", "Category"]])


# 2. Products containing 'lap' or 'tab'
lap_tab_products = df[
    df["Product"].str.contains("lap|tab", case=False, na=False)
]

print("\nProducts containing 'lap' or 'tab':")
print(lap_tab_products[["Product", "Category"]])


# 3. Products with more than 6 characters
long_products = df[
    df["Product"].str.len() > 6
]

print("\nProducts with more than 6 characters:")
print(long_products[["Product", "Category"]])


# 4. Products whose Category is not Clothing
non_clothing = df[
    df["Category"] != "Clothing"
]

print("\nNon-Clothing products:")
print(non_clothing[["Product", "Category"]])


# 5. Combined condition
result = df[
    (
        df["Product"].str.contains("lap|tab", case=False, na=False)
    )
    &
    (
        df["Product"].str.len() > 6
    )
    &
    (
        df["Category"] != "Clothing"
    )
]

print("\nFinal matching non-Clothing products:")
print(result[["Product", "Category"]])

Products containing 'phone':
      Product     Category
4  Headphones  Electronics

Products containing 'lap' or 'tab':
   Product     Category
0   Laptop  Electronics
10  Tablet  Electronics

Products with more than 6 characters:
       Product     Category
1      T-Shirt     Clothing
4   Headphones  Electronics
6      Monitor  Electronics
9     Keyboard  Electronics
13  Smartwatch  Electronics
14     T-Shirt     Clothing

Non-Clothing products:
       Product     Category
0       Laptop  Electronics
2       Mobile  Electronics
3        Mixer         Home
4   Headphones  Electronics
6      Monitor  Electronics
7        Chair         Home
9     Keyboard  Electronics
10      Tablet  Electronics
12        Lamp         Home
13  Smartwatch  Electronics

Final matching non-Clothing products:
Empty DataFrame
Columns: [Product, Category]
Index: []

In [306]:

#Task 5 — Price & Quantity Investigation
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("ECommerce_Orders_.csv")

# Create Price_Category
conditions = [
    df["Unit_Price"] < 2000,
    (df["Unit_Price"] >= 2000) & (df["Unit_Price"] <= 10000),
    (df["Unit_Price"] > 10000) & (df["Unit_Price"] <= 30000),
    df["Unit_Price"] > 30000
]

choices = [
    "Budget",
    "Mid Range",
    "Premium",
    "Luxury"
]

df["Price_Category"] = np.select(
    conditions,
    choices,
    default="Unknown"
)

# Find Luxury products with Quantity > 1
luxury_products = df[
    (df["Price_Category"] == "Luxury") &
    (df["Quantity"] > 1)
]

# Sort by Unit_Price descending
result = luxury_products.sort_values(
    by="Unit_Price",
    ascending=False
)

# Display required columns
result = result[
    ["Product", "Category", "Quantity", "Unit_Price", "Price_Category"]
]

print(result)

Empty DataFrame
Columns: [Product, Category, Quantity, Unit_Price, Price_Category]
Index: []

In [307]:
#Task 5 — Price & Quantity Investigation
conditions=[
    (df["Unit_Price"]<2000),
    (df["Unit_Price"]>=2000) &(df["Unit_Price"]<10000),
    (df["Unit_Price"]>=10000)& (df["Unit_Price"]<30000),
    df["Unit_Price"]>30000]
choice=["Budget","Mid Range","Premimum","Luxury"]
df["Price_Category"]=np.select(conditions,choice,default="Unknown")
df["Price_Category"]

0        Luxury
1        Budget
2      Premimum
3     Mid Range
4     Mid Range
5     Mid Range
6      Premimum
7     Mid Range
8     Mid Range
9        Budget
10      Unknown
11    Mid Range
12       Budget
13     Premimum
14       Budget
Name: Price_Category, dtype: str

In [308]:
result=(df["Price_Category"]==("Luxury"))&(df["Quantity"]>1)
print(df[result])
print(df[["Product","Category","Quantity","Unit_Price","Price_Category"]])

Empty DataFrame
Columns: [Order_ID, Customer, City, Category, Product, Quantity, Unit_Price, Payment_Mode, Rating, Price_Category]
Index: []
       Product     Category  Quantity  Unit_Price Price_Category
0       Laptop  Electronics         1       65000         Luxury
1      T-Shirt     Clothing         2        1200         Budget
2       Mobile  Electronics         1       25000       Premimum
3        Mixer         Home         1        5000      Mid Range
4   Headphones  Electronics         2        3000      Mid Range
5        Jeans     Clothing         1        2200      Mid Range
6      Monitor  Electronics         1       18000       Premimum
7        Chair         Home         2        7500      Mid Range
8        Shoes     Clothing         1        2500      Mid Range
9     Keyboard  Electronics         3        1500         Budget
10      Tablet  Electronics         1       30000        Unknown
11      Jacket     Clothing         1        3500      Mid Range
12        Lamp         Home         2        1800         Budget
13  Smartwatch  Electronics         1       12000       Premimum
14     T-Shirt     Clothing         2        1200         Budget

In [309]:
print(df.sort_values("Unit_Price",ascending=False))

   Order_ID      Customer       City     Category     Product  Quantity  \
0    ORD001  Rahul Sharma  Hyderabad  Electronics      Laptop         1
10   ORD011   Arjun Kumar  Hyderabad  Electronics      Tablet         1
2    ORD003   Arjun Kumar  Hyderabad  Electronics      Mobile         1
6    ORD007  Anjali Singh     Mumbai  Electronics     Monitor         1
13   ORD014  Anjali Singh     Mumbai  Electronics  Smartwatch         1
7    ORD008  Vikram Patel  Bangalore         Home       Chair         2
3    ORD004     Sneha Rao    Chennai         Home       Mixer         1
11   ORD012     Sneha Rao    Chennai     Clothing      Jacket         1
4    ORD005     Kiran Das       Pune  Electronics  Headphones         2
8    ORD009   Priya Reddy  Bangalore     Clothing       Shoes         1
5    ORD006  Rahul Sharma  Hyderabad     Clothing       Jeans         1
12   ORD013     Kiran Das       Pune         Home        Lamp         2
9    ORD010   Rohit Verma      Delhi  Electronics    Keyboard         3
1    ORD002   Priya Reddy  Bangalore     Clothing     T-Shirt         2
14   ORD015  Vikram Patel  Bangalore     Clothing     T-Shirt         2

    Unit_Price Payment_Mode  Rating Price_Category
0        65000          UPI       5         Luxury
10       30000          UPI       5        Unknown
2        25000          UPI       5       Premimum
6        18000         Card       4       Premimum
13       12000          UPI       5       Premimum
7         7500          UPI       3      Mid Range
3         5000         Cash       3      Mid Range
11        3500         Card       4      Mid Range
4         3000         Card       4      Mid Range
8         2500         Card       4      Mid Range
5         2200          UPI       5      Mid Range
12        1800         Cash       3         Budget
9         1500         Cash       5         Budget
1         1200         Card       4         Budget
14        1200         Card       4         Budget

In [327]:
#Task 6 — Employee Eligibility Analysis
df = pd.read_csv("Employee_Data_.csv")
print(df[["Employee_ID","Name","Experience","Salary","Performance"]])
result=(df["Department"]=="IT")&(df["Experience"]>=5)&(df["Performance"]>4.3)&(df["Salary"]>=70000)
print(df[result.sort_values(ascending=False)])

    Employee_ID    Name  Experience  Salary  Performance
0           101   Rahul           3   60000          4.5
1           102   Priya           5   75000          4.2
2           103   Arjun           2   50000          4.8
3           104   Sneha           7   90000          3.9
4           105   Kiran           4   65000          4.1
5           106  Anjali           6   85000          4.7
6           107  Vikram           3   55000          3.8
7           108   Rohit           2   48000          3.5
8           109   Meena           8   95000          4.6
9           110  Suresh           5   70000          4.3
10          111   Pooja           4   62000          4.0
11          112    Amit           6   80000          4.9
    Employee_ID    Name Department  Experience  Salary  Performance
5           106  Anjali         IT           6   85000          4.7
11          112    Amit         IT           6   80000          4.9

C:\Users\DELL\AppData\Local\Temp\ipykernel_17008\2226137034.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(df[result.sort_values(ascending=False)])

In [328]:
# Task 7 — Salary Band & Promotion Flag
conditions = [
    (df["Salary"]<=60000),
    (df["Salary"]>60000)&(df["Salary"]<=75000),
    (df["Salary"]>75000)&(df["Salary"]<90000),
    (df["Salary"]>=90000)]
choice = ["Entry","Mid","Senior","Lead"]
df["Salary_band"] = np.select(conditions,choice ,default="Unknown")
print(df)

    Employee_ID    Name Department  Experience  Salary  Performance  \
0           101   Rahul         IT           3   60000          4.5
1           102   Priya         HR           5   75000          4.2
2           103   Arjun         IT           2   50000          4.8
3           104   Sneha    Finance           7   90000          3.9
4           105   Kiran      Sales           4   65000          4.1
5           106  Anjali         IT           6   85000          4.7
6           107  Vikram      Sales           3   55000          3.8
7           108   Rohit         HR           2   48000          3.5
8           109   Meena    Finance           8   95000          4.6
9           110  Suresh         IT           5   70000          4.3
10          111   Pooja      Sales           4   62000          4.0
11          112    Amit         IT           6   80000          4.9

   Salary_band
0        Entry
1          Mid
2        Entry
3         Lead
4          Mid
5       Senior
6        Entry
7        Entry
8         Lead
9          Mid
10         Mid
11      Senior

In [ ]:
df["Promotion_Flag"]=np.where((df["Experience"]>=5)&(df["Performance"]>=4.5),"Review","No Review") 
df

,Employee_ID,Name,Department,Experience,Salary,Performance,salary_band,Promotion_Flag,Salary_band
0,101,Rahul,IT,3,60000,4.5,Entry,No Review,Entry
1,102,Priya,HR,5,75000,4.2,Mid,No Review,Mid
2,103,Arjun,IT,2,50000,4.8,Entry,No Review,Entry
3,104,Sneha,Finance,7,90000,3.9,Lead,No Review,Lead
4,105,Kiran,Sales,4,65000,4.1,Mid,No Review,Mid
5,106,Anjali,IT,6,85000,4.7,Senior,Review,Senior
6,107,Vikram,Sales,3,55000,3.8,Entry,No Review,Entry
7,108,Rohit,HR,2,48000,3.5,Entry,No Review,Entry
8,109,Meena,Finance,8,95000,4.6,Lead,Review,Lead
9,110,Suresh,IT,5,70000,4.3,Mid,No Review,Mid
10,111,Pooja,Sales,4,62000,4.0,Mid,No Review,Mid
11,112,Amit,IT,6,80000,4.9,Senior,Review,Senior

In [ ]:
k=df[["Name","Department","Experience","Salary","Performance","Salary_band","Promotion_Flag"]]
print(k)

      Name Department  Experience  Salary  Performance Salary_band  \
0    Rahul         IT           3   60000          4.5       Entry
1    Priya         HR           5   75000          4.2         Mid
2    Arjun         IT           2   50000          4.8       Entry
3    Sneha    Finance           7   90000          3.9        Lead
4    Kiran      Sales           4   65000          4.1         Mid
5   Anjali         IT           6   85000          4.7      Senior
6   Vikram      Sales           3   55000          3.8       Entry
7    Rohit         HR           2   48000          3.5       Entry
8    Meena    Finance           8   95000          4.6        Lead
9   Suresh         IT           5   70000          4.3         Mid
10   Pooja      Sales           4   62000          4.0         Mid
11    Amit         IT           6   80000          4.9      Senior

   Promotion_Flag
0       No Review
1       No Review
2       No Review
3       No Review
4       No Review
5          Review
6       No Review
7       No Review
8          Review
9       No Review
10      No Review
11         Review

In [ ]:
"""
Task 8 — Employee Data Cleaning
Dataset: Employee Data
Concepts: isna(), fillna(), median(), duplicated(), drop_duplicates()
•	Create a dirty copy of the employee dataset.
•	Set Salary at row index 2 to missing and Department at row index 5 to missing.
•	Append a duplicate of row index 1.
•	Find missing values and duplicate records.
•	Remove duplicates.
•	Fill missing Salary using the median Salary.
•	Fill missing Department with 'Unknown'.
•	Verify that no missing values or duplicates remain.
"""

"\nTask 8 — Employee Data Cleaning\nDataset: Employee Data\nConcepts: isna(), fillna(), median(), duplicated(), drop_duplicates()\n•\tCreate a dirty copy of the employee dataset.\n•\tSet Salary at row index 2 to missing and Department at row index 5 to missing.\n•\tAppend a duplicate of row index 1.\n•\tFind missing values and duplicate records.\n•\tRemove duplicates.\n•\tFill missing Salary using the median Salary.\n•\tFill missing Department with 'Unknown'.\n•\tVerify that no missing values or duplicates remain.\n"

In [ ]:
print(df.to_string())

    Employee_ID    Name Department  Experience  Salary  Performance salary_band Promotion_Flag Salary_band
0           101   Rahul         IT           3   60000          4.5       Entry      No Review       Entry
1           102   Priya         HR           5   75000          4.2         Mid      No Review         Mid
2           103   Arjun         IT           2   50000          4.8       Entry      No Review       Entry
3           104   Sneha    Finance           7   90000          3.9        Lead      No Review        Lead
4           105   Kiran      Sales           4   65000          4.1         Mid      No Review         Mid
5           106  Anjali         IT           6   85000          4.7      Senior         Review      Senior
6           107  Vikram      Sales           3   55000          3.8       Entry      No Review       Entry
7           108   Rohit         HR           2   48000          3.5       Entry      No Review       Entry
8           109   Meena    Finance           8   95000          4.6        Lead         Review        Lead
9           110  Suresh         IT           5   70000          4.3         Mid      No Review         Mid
10          111   Pooja      Sales           4   62000          4.0         Mid      No Review         Mid
11          112    Amit         IT           6   80000          4.9      Senior         Review      Senior

In [ ]:
df=pd.read_csv("Employee_Data_.csv")
dirty = df.copy()
print(id(dirty))
print(id(df))
print(dirty is df)

1724124143952
1724124141360
False

In [ ]:
dirty.at[2,"Salary"]=np.nan
dirty.at[5,"Department"]=np.nan
print(dirty)

    Employee_ID    Name Department  Experience   Salary  Performance
0           101   Rahul         IT           3  60000.0          4.5
1           102   Priya         HR           5  75000.0          4.2
2           103   Arjun         IT           2      NaN          4.8
3           104   Sneha    Finance           7  90000.0          3.9
4           105   Kiran      Sales           4  65000.0          4.1
5           106  Anjali        NaN           6  85000.0          4.7
6           107  Vikram      Sales           3  55000.0          3.8
7           108   Rohit         HR           2  48000.0          3.5
8           109   Meena    Finance           8  95000.0          4.6
9           110  Suresh         IT           5  70000.0          4.3
10          111   Pooja      Sales           4  62000.0          4.0
11          112    Amit         IT           6  80000.0          4.9

In [ ]:
dup = dirty.loc[[1]]
dirty=pd.concat([dirty,dup],ignore_index=True)
print(dirty)

    Employee_ID    Name Department  Experience   Salary  Performance
0           101   Rahul         IT           3  60000.0          4.5
1           102   Priya         HR           5  75000.0          4.2
2           103   Arjun         IT           2      NaN          4.8
3           104   Sneha    Finance           7  90000.0          3.9
4           105   Kiran      Sales           4  65000.0          4.1
5           106  Anjali        NaN           6  85000.0          4.7
6           107  Vikram      Sales           3  55000.0          3.8
7           108   Rohit         HR           2  48000.0          3.5
8           109   Meena    Finance           8  95000.0          4.6
9           110  Suresh         IT           5  70000.0          4.3
10          111   Pooja      Sales           4  62000.0          4.0
11          112    Amit         IT           6  80000.0          4.9
12          102   Priya         HR           5  75000.0          4.2

In [ ]:
#print(np.select(dirty.isna(),dirty,0,default="Unknown"))
df = dirty.isna().any(axis=1)
print(len(dirty[df]))
dirty[df]

In [ ]:
print(dirty)
df = dirty.duplicated()
print(len(dirty[df]))
dirty[df]

0     False
1     False
2      True
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10    False
11    False
12    False
dtype: bool
11

1     False
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10    False
11    False
12    False
dtype: bool

In [ ]:

print(dirty)
dirty=dirty.drop_duplicates()
print(len(dirty))
#print(len(dirty[df]))
dirty

    Employee_ID    Name Department  Experience   Salary  Performance
0           101   Rahul         IT           3  60000.0          4.5
1           102   Priya         HR           5  75000.0          4.2
2           103   Arjun         IT           2      NaN          4.8
3           104   Sneha    Finance           7  90000.0          3.9
4           105   Kiran      Sales           4  65000.0          4.1
5           106  Anjali        NaN           6  85000.0          4.7
6           107  Vikram      Sales           3  55000.0          3.8
7           108   Rohit         HR           2  48000.0          3.5
8           109   Meena    Finance           8  95000.0          4.6
9           110  Suresh         IT           5  70000.0          4.3
10          111   Pooja      Sales           4  62000.0          4.0
11          112    Amit         IT           6  80000.0          4.9
12

    Employee_ID    Name Department  Experience   Salary  Performance
0           101   Rahul         IT           3  60000.0          4.5
1           102   Priya         HR           5  75000.0          4.2
2           103   Arjun         IT           2      NaN          4.8
3           104   Sneha    Finance           7  90000.0          3.9
4           105   Kiran      Sales           4  65000.0          4.1
5           106  Anjali        NaN           6  85000.0          4.7
6           107  Vikram      Sales           3  55000.0          3.8
7           108   Rohit         HR           2  48000.0          3.5
8           109   Meena    Finance           8  95000.0          4.6
9           110  Suresh         IT           5  70000.0          4.3
10          111   Pooja      Sales           4  62000.0          4.0
11          112    Amit         IT           6  80000.0          4.9

In [ ]:
salary_median = dirty["Salary"].median()
print(salary_median)
dirty["Salary"] = dirty["Salary"].fillna(salary_median)
print(dirty)

67500.0
0                                                     False
1                                                     False
2                                                      True
3                                                     False
4                                                     False
5                                                      True
6                                                     False
7                                                     False
8                                                     False
9                                                     False
10                                                    False
11                                                    False
12                                                    False
Salary    0     60000
1     75000
2     50000
3     9000...
dtype: object

In [ ]:
dirty.info
df.info

<bound method DataFrame.info of     Employee_ID    Name Department  Experience  Salary  Performance  \
0           101   Rahul         IT           3   60000          4.5
1           102   Priya         HR           5   75000          4.2
2           103   Arjun         IT           2   50000          4.8
3           104   Sneha    Finance           7   90000          3.9
4           105   Kiran      Sales           4   65000          4.1
5           106  Anjali         IT           6   85000          4.7
6           107  Vikram      Sales           3   55000          3.8
7           108   Rohit         HR           2   48000          3.5
8           109   Meena    Finance           8   95000          4.6
9           110  Suresh         IT           5   70000          4.3
10          111   Pooja      Sales           4   62000          4.0
11          112    Amit         IT           6   80000          4.9

   Salary_band
0        Entry
1          Mid
2        Entry
3         Lead
4          Mid
5       Senior
6        Entry
7        Entry
8         Lead
9          Mid
10         Mid
11      Senior  >

In [ ]:
#Task 9 — Student Risk Analysis
# Dataset: Student Performance
# Concepts: Arithmetic, calculated columns, conditional classification
# •	Create Final_Score = Assignment_Score × 0.40 + Exam_Score × 0.60.
# •	Create Status: >=85 = Excellent; 70–84 = Good; 50–69 = Needs Improvement; <50 = At Risk.
# •	Find students where Attendance < 80 AND Final_Score < 70.
# •	Display Student_ID, Name, Course, Attendance, Final_Score, and Status.


student=pd.read_csv("Student_Performance.csv")
student

  Student_ID    Name      Course  Attendance  Assignment_Score  Exam_Score
0       S001   Rahul      Python          92                85          88
1       S002   Priya      Python          85                78          80
2       S003   Arjun  JavaScript          78                65          70
3       S004   Sneha      Python          95                92          94
4       S005   Kiran         SQL          88                88          91
5       S006  Anjali      Python          91                90          93
6       S007  Vikram         SQL          72                60          58
7       S008   Rohit  JavaScript          89                75          78
8       S009   Meena      Python          96                95          96
9       S010   Pooja         SQL          80                82          85

In [ ]:
student["Final_Score"]=student["Assignment_Score"]*0.40+student["Exam_Score"]*0.60
student

,Student_ID,Name,Course,Attendance,Assignment_Score,Exam_Score,Final_Score
0,S001,Rahul,Python,92,85,88,86.8
1,S002,Priya,Python,85,78,80,79.2
2,S003,Arjun,JavaScript,78,65,70,68.0
3,S004,Sneha,Python,95,92,94,93.2
4,S005,Kiran,SQL,88,88,91,89.8
5,S006,Anjali,Python,91,90,93,91.8
6,S007,Vikram,SQL,72,60,58,58.8
7,S008,Rohit,JavaScript,89,75,78,76.8
8,S009,Meena,Python,96,95,96,95.6
9,S010,Pooja,SQL,80,82,85,83.8

In [ ]:
conditions=[
    (student["Final_Score"]>=85),
    (student["Final_Score"]>=70)&(student["Final_Score"]<85),
    (student["Final_Score"]>=50)&(student["Final_Score"]<70),
    (student["Final_Score"]<50)]
choice=["Excellent","Good","NI","Risk"]
student["Status"]=np.select(conditions,choice,default="Unknown")
student

,Student_ID,Name,Course,Attendance,Assignment_Score,Exam_Score,Final_Score,Status
0,S001,Rahul,Python,92,85,88,86.8,Excellent
1,S002,Priya,Python,85,78,80,79.2,Good
2,S003,Arjun,JavaScript,78,65,70,68.0,NI
3,S004,Sneha,Python,95,92,94,93.2,Excellent
4,S005,Kiran,SQL,88,88,91,89.8,Excellent
5,S006,Anjali,Python,91,90,93,91.8,Excellent
6,S007,Vikram,SQL,72,60,58,58.8,NI
7,S008,Rohit,JavaScript,89,75,78,76.8,Good
8,S009,Meena,Python,96,95,96,95.6,Excellent
9,S010,Pooja,SQL,80,82,85,83.8,Good

In [ ]:
student= student[(student["Attendance"] < 80) & (student["Final_Score"] < 70)]
student

,Student_ID,Name,Course,Attendance,Assignment_Score,Exam_Score,Final_Score,Status
2,S003,Arjun,JavaScript,78,65,70,68.0,NI
6,S007,Vikram,SQL,72,60,58,58.8,NI

In [ ]:
print(student[["Student_ID","Name","Course","Attendance","Final_Score","Status"]])

  Student_ID    Name      Course  Attendance  Final_Score Status
2       S003   Arjun  JavaScript          78         68.0     NI
6       S007  Vikram         SQL          72         58.8     NI

In [ ]:
# Task 10 — Complete Analyst Challenge
# Dataset: E-Commerce Orders
# Concepts: Combined Day 1–8 workflow; no groupby() or aggregation
# •	Create Revenue = Quantity × Unit_Price.
# •	Create Discount_Rate: Revenue >= 50000 = 15%; Revenue >= 20000 = 10%; otherwise 5%.
# •	Calculate Discount_Amount and Final_Revenue.
# •	Create Customer_Status: Rating >= 4 = Satisfied; otherwise Needs Attention.
# •	Find orders where Category = Electronics AND Final_Revenue > 20000 AND Rating >= 4 AND Payment_Mode = UPI.
# •	Sort qualifying orders by Final_Revenue descending.
# •	Return Order_ID, Customer, City, Product, Quantity, Revenue, Discount_Amount, Final_Revenue, and Rating.
# •	Create Order_Label such as: ORD001 - Laptop - ₹55250

In [314]:
df=pd.read_csv("ECommerce_Orders_.csv")
df

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Payment_Mode,Rating
0,ORD001,Rahul Sharma,Hyderabad,Electronics,Laptop,1,65000,UPI,5
1,ORD002,Priya Reddy,Bangalore,Clothing,T-Shirt,2,1200,Card,4
2,ORD003,Arjun Kumar,Hyderabad,Electronics,Mobile,1,25000,UPI,5
3,ORD004,Sneha Rao,Chennai,Home,Mixer,1,5000,Cash,3
4,ORD005,Kiran Das,Pune,Electronics,Headphones,2,3000,Card,4
5,ORD006,Rahul Sharma,Hyderabad,Clothing,Jeans,1,2200,UPI,5
6,ORD007,Anjali Singh,Mumbai,Electronics,Monitor,1,18000,Card,4
7,ORD008,Vikram Patel,Bangalore,Home,Chair,2,7500,UPI,3
8,ORD009,Priya Reddy,Bangalore,Clothing,Shoes,1,2500,Card,4
9,ORD010,Rohit Verma,Delhi,Electronics,Keyboard,3,1500,Cash,5
10,ORD011,Arjun Kumar,Hyderabad,Electronics,Tablet,1,30000,UPI,5
11,ORD012,Sneha Rao,Chennai,Clothing,Jacket,1,3500,Card,4
12,ORD013,Kiran Das,Pune,Home,Lamp,2,1800,Cash,3
13,ORD014,Anjali Singh,Mumbai,Electronics,Smartwatch,1,12000,UPI,5
14,ORD015,Vikram Patel,Bangalore,Clothing,T-Shirt,2,1200,Card,4

In [315]:
df["Revenue"]=df["Quantity"]*df["Unit_Price"]
cond=[
    df["Revenue"]>=50000,
    (df["Revenue"]>=20000)&(df["Revenue"]<50000)
]
choice=[0.15,0.10]
df["Discount_Amount"]=np.select(cond,choice,default=[0.5])
df["Final_Revenue"] = df["Revenue"] - df["Discount_Amount"]
df["Customer_Status"]=np.where(df["Rating"] >= 4,"Satisfied","Needs Attention")
df

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Payment_Mode,Rating,Revenue,Discount_Amount,Final_Revenue,Customer_Status
0,ORD001,Rahul Sharma,Hyderabad,Electronics,Laptop,1,65000,UPI,5,65000,0.15,64999.85,Satisfied
1,ORD002,Priya Reddy,Bangalore,Clothing,T-Shirt,2,1200,Card,4,2400,0.50,2399.50,Satisfied
2,ORD003,Arjun Kumar,Hyderabad,Electronics,Mobile,1,25000,UPI,5,25000,0.10,24999.90,Satisfied
3,ORD004,Sneha Rao,Chennai,Home,Mixer,1,5000,Cash,3,5000,0.50,4999.50,Needs Attention
4,ORD005,Kiran Das,Pune,Electronics,Headphones,2,3000,Card,4,6000,0.50,5999.50,Satisfied
5,ORD006,Rahul Sharma,Hyderabad,Clothing,Jeans,1,2200,UPI,5,2200,0.50,2199.50,Satisfied
6,ORD007,Anjali Singh,Mumbai,Electronics,Monitor,1,18000,Card,4,18000,0.50,17999.50,Satisfied
7,ORD008,Vikram Patel,Bangalore,Home,Chair,2,7500,UPI,3,15000,0.50,14999.50,Needs Attention
8,ORD009,Priya Reddy,Bangalore,Clothing,Shoes,1,2500,Card,4,2500,0.50,2499.50,Satisfied
9,ORD010,Rohit Verma,Delhi,Electronics,Keyboard,3,1500,Cash,5,4500,0.50,4499.50,Satisfied
10,ORD011,Arjun Kumar,Hyderabad,Electronics,Tablet,1,30000,UPI,5,30000,0.10,29999.90,Satisfied
11,ORD012,Sneha Rao,Chennai,Clothing,Jacket,1,3500,Card,4,3500,0.50,3499.50,Satisfied
12,ORD013,Kiran Das,Pune,Home,Lamp,2,1800,Cash,3,3600,0.50,3599.50,Needs Attention
13,ORD014,Anjali Singh,Mumbai,Electronics,Smartwatch,1,12000,UPI,5,12000,0.50,11999.50,Satisfied
14,ORD015,Vikram Patel,Bangalore,Clothing,T-Shirt,2,1200,Card,4,2400,0.50,2399.50,Satisfied

In [316]:
qualifying_filter = (
    (df["Category"] == "Electronics")
    & (df["Final_Revenue"] > 20000)
    & (df["Rating"] >= 4)
    & (df["Payment_Mode"] == "UPI")
)
df[qualifying_filter]

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Payment_Mode,Rating,Revenue,Discount_Amount,Final_Revenue,Customer_Status
0,ORD001,Rahul Sharma,Hyderabad,Electronics,Laptop,1,65000,UPI,5,65000,0.15,64999.85,Satisfied
2,ORD003,Arjun Kumar,Hyderabad,Electronics,Mobile,1,25000,UPI,5,25000,0.10,24999.90,Satisfied
10,ORD011,Arjun Kumar,Hyderabad,Electronics,Tablet,1,30000,UPI,5,30000,0.10,29999.90,Satisfied

In [319]:
df=df.sort_values(by="Final_Revenue",ascending=False)
df

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Payment_Mode,Rating,Revenue,Discount_Amount,Final_Revenue,Customer_Status
0,ORD001,Rahul Sharma,Hyderabad,Electronics,Laptop,1,65000,UPI,5,65000,0.15,64999.85,Satisfied
10,ORD011,Arjun Kumar,Hyderabad,Electronics,Tablet,1,30000,UPI,5,30000,0.10,29999.90,Satisfied
2,ORD003,Arjun Kumar,Hyderabad,Electronics,Mobile,1,25000,UPI,5,25000,0.10,24999.90,Satisfied
6,ORD007,Anjali Singh,Mumbai,Electronics,Monitor,1,18000,Card,4,18000,0.50,17999.50,Satisfied
7,ORD008,Vikram Patel,Bangalore,Home,Chair,2,7500,UPI,3,15000,0.50,14999.50,Needs Attention
13,ORD014,Anjali Singh,Mumbai,Electronics,Smartwatch,1,12000,UPI,5,12000,0.50,11999.50,Satisfied
4,ORD005,Kiran Das,Pune,Electronics,Headphones,2,3000,Card,4,6000,0.50,5999.50,Satisfied
3,ORD004,Sneha Rao,Chennai,Home,Mixer,1,5000,Cash,3,5000,0.50,4999.50,Needs Attention
9,ORD010,Rohit Verma,Delhi,Electronics,Keyboard,3,1500,Cash,5,4500,0.50,4499.50,Satisfied
12,ORD013,Kiran Das,Pune,Home,Lamp,2,1800,Cash,3,3600,0.50,3599.50,Needs Attention
11,ORD012,Sneha Rao,Chennai,Clothing,Jacket,1,3500,Card,4,3500,0.50,3499.50,Satisfied
8,ORD009,Priya Reddy,Bangalore,Clothing,Shoes,1,2500,Card,4,2500,0.50,2499.50,Satisfied
1,ORD002,Priya Reddy,Bangalore,Clothing,T-Shirt,2,1200,Card,4,2400,0.50,2399.50,Satisfied
14,ORD015,Vikram Patel,Bangalore,Clothing,T-Shirt,2,1200,Card,4,2400,0.50,2399.50,Satisfied
5,ORD006,Rahul Sharma,Hyderabad,Clothing,Jeans,1,2200,UPI,5,2200,0.50,2199.50,Satisfied

In [323]:
df["Order_Label"] = (
    df["Order_ID"].astype(str)
    + " - "
    + df["Product"].astype(str)
    + " - ₹"
    + df["Final_Revenue"].round(2).astype(str)
)
df

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Payment_Mode,Rating,Revenue,Discount_Amount,Final_Revenue,Customer_Status,Order_Label
0,ORD001,Rahul Sharma,Hyderabad,Electronics,Laptop,1,65000,UPI,5,65000,0.15,64999.85,Satisfied,ORD001 - Laptop - ₹64999.85
10,ORD011,Arjun Kumar,Hyderabad,Electronics,Tablet,1,30000,UPI,5,30000,0.10,29999.90,Satisfied,ORD011 - Tablet - ₹29999.9
2,ORD003,Arjun Kumar,Hyderabad,Electronics,Mobile,1,25000,UPI,5,25000,0.10,24999.90,Satisfied,ORD003 - Mobile - ₹24999.9
6,ORD007,Anjali Singh,Mumbai,Electronics,Monitor,1,18000,Card,4,18000,0.50,17999.50,Satisfied,ORD007 - Monitor - ₹17999.5
7,ORD008,Vikram Patel,Bangalore,Home,Chair,2,7500,UPI,3,15000,0.50,14999.50,Needs Attention,ORD008 - Chair - ₹14999.5
13,ORD014,Anjali Singh,Mumbai,Electronics,Smartwatch,1,12000,UPI,5,12000,0.50,11999.50,Satisfied,ORD014 - Smartwatch - ₹11999.5
4,ORD005,Kiran Das,Pune,Electronics,Headphones,2,3000,Card,4,6000,0.50,5999.50,Satisfied,ORD005 - Headphones - ₹5999.5
3,ORD004,Sneha Rao,Chennai,Home,Mixer,1,5000,Cash,3,5000,0.50,4999.50,Needs Attention,ORD004 - Mixer - ₹4999.5
9,ORD010,Rohit Verma,Delhi,Electronics,Keyboard,3,1500,Cash,5,4500,0.50,4499.50,Satisfied,ORD010 - Keyboard - ₹4499.5
12,ORD013,Kiran Das,Pune,Home,Lamp,2,1800,Cash,3,3600,0.50,3599.50,Needs Attention,ORD013 - Lamp - ₹3599.5
11,ORD012,Sneha Rao,Chennai,Clothing,Jacket,1,3500,Card,4,3500,0.50,3499.50,Satisfied,ORD012 - Jacket - ₹3499.5
8,ORD009,Priya Reddy,Bangalore,Clothing,Shoes,1,2500,Card,4,2500,0.50,2499.50,Satisfied,ORD009 - Shoes - ₹2499.5
1,ORD002,Priya Reddy,Bangalore,Clothing,T-Shirt,2,1200,Card,4,2400,0.50,2399.50,Satisfied,ORD002 - T-Shirt - ₹2399.5
14,ORD015,Vikram Patel,Bangalore,Clothing,T-Shirt,2,1200,Card,4,2400,0.50,2399.50,Satisfied,ORD015 - T-Shirt - ₹2399.5
5,ORD006,Rahul Sharma,Hyderabad,Clothing,Jeans,1,2200,UPI,5,2200,0.50,2199.50,Satisfied,ORD006 - Jeans - ₹2199.5

In [324]:
df[[
    "Order_ID",
    "Customer",
    "City",
    "Product",
    "Quantity",
    "Revenue",
    "Discount_Amount",
    "Final_Revenue",
    "Rating",
    "Order_Label",
]]

,Order_ID,Customer,City,Product,Quantity,Revenue,Discount_Amount,Final_Revenue,Rating,Order_Label
0,ORD001,Rahul Sharma,Hyderabad,Laptop,1,65000,0.15,64999.85,5,ORD001 - Laptop - ₹64999.85
10,ORD011,Arjun Kumar,Hyderabad,Tablet,1,30000,0.10,29999.90,5,ORD011 - Tablet - ₹29999.9
2,ORD003,Arjun Kumar,Hyderabad,Mobile,1,25000,0.10,24999.90,5,ORD003 - Mobile - ₹24999.9
6,ORD007,Anjali Singh,Mumbai,Monitor,1,18000,0.50,17999.50,4,ORD007 - Monitor - ₹17999.5
7,ORD008,Vikram Patel,Bangalore,Chair,2,15000,0.50,14999.50,3,ORD008 - Chair - ₹14999.5
13,ORD014,Anjali Singh,Mumbai,Smartwatch,1,12000,0.50,11999.50,5,ORD014 - Smartwatch - ₹11999.5
4,ORD005,Kiran Das,Pune,Headphones,2,6000,0.50,5999.50,4,ORD005 - Headphones - ₹5999.5
3,ORD004,Sneha Rao,Chennai,Mixer,1,5000,0.50,4999.50,3,ORD004 - Mixer - ₹4999.5
9,ORD010,Rohit Verma,Delhi,Keyboard,3,4500,0.50,4499.50,5,ORD010 - Keyboard - ₹4499.5
12,ORD013,Kiran Das,Pune,Lamp,2,3600,0.50,3599.50,3,ORD013 - Lamp - ₹3599.5
11,ORD012,Sneha Rao,Chennai,Jacket,1,3500,0.50,3499.50,4,ORD012 - Jacket - ₹3499.5
8,ORD009,Priya Reddy,Bangalore,Shoes,1,2500,0.50,2499.50,4,ORD009 - Shoes - ₹2499.5
1,ORD002,Priya Reddy,Bangalore,T-Shirt,2,2400,0.50,2399.50,4,ORD002 - T-Shirt - ₹2399.5
14,ORD015,Vikram Patel,Bangalore,T-Shirt,2,2400,0.50,2399.50,4,ORD015 - T-Shirt - ₹2399.5
5,ORD006,Rahul Sharma,Hyderabad,Jeans,1,2200,0.50,2199.50,5,ORD006 - Jeans - ₹2199.5